name: Build

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: .exe
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mchprs-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/mchprs${{ matrix.ext }}

  build-macos-universal:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mchprs-x86_64-apple-darwin
          path: x86_64
      - uses: actions/download-artifact@v4
        with:
          name: mchprs-aarch64-apple-darwin
          path: aarch64

      - name: Create universal binary
        run: lipo -create -output mchprs x86_64/mchprs aarch64/mchprs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mchprs-universal-apple-darwin
          path: mchprs

  preview:
    needs: [build, build-macos-universal]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: target
      - name: Install mmv
        run: sudo apt-get install -y mmv
      - name: Reorganize artifacts
        run: mmv "target/*/*" "dist/*-#1.*"

      - name: Create preview release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release delete preview --yes || true
          gh release create preview \
            --repo="${GITHUB_REPOSITORY}" \
            --prerelease \
            --title "${GITHUB_REPOSITORY} Preview Build" \
            --notes "🚧 **This is a preview build of the latest commit.**" \
            dist/*

  release:
    needs: [build, build-macos-universal]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${tag} \
            --repo="${GITHUB_REPOSITORY}" \
            --title "${GITHUB_REPOSITORY} ${tag#v}" \
            --generate-notes
            **/*
